"""
document_service.py — generates a 4-document switch package as a zip of PDFs.

Documents:
  1. member_letter.pdf         — to the patient
  2. prescriber_letter.pdf     — to the prescribing physician
  3. pharmacy_notice.pdf       — to the dispensing pharmacy
  4. internal_memo.pdf         — internal payer UM/PA memo

Uses reportlab for PDF generation; all output is in-memory (no temp files).
"""

from __future__ import annotations

import io
import zipfile
from datetime import date

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)


# ── Shared style helpers ──────────────────────────────────────────────────────

def _styles():
    base = getSampleStyleSheet()
    styles = {
        "h1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=16, spaceAfter=4,
                             textColor=colors.HexColor("#1a3a5c")),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=12, spaceAfter=4,
                             textColor=colors.HexColor("#1a3a5c")),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10, leading=14,
                               spaceAfter=6),
        "small": ParagraphStyle("Small", parent=base["Normal"], fontSize=8, leading=11,
                                textColor=colors.HexColor("#666666")),
        "bold": ParagraphStyle("Bold", parent=base["Normal"], fontSize=10, leading=14,
                               spaceAfter=6, fontName="Helvetica-Bold"),
        "disclaimer": ParagraphStyle("Disclaimer", parent=base["Normal"], fontSize=8,
                                     leading=11, textColor=colors.HexColor("#888888"),
                                     borderColor=colors.HexColor("#cccccc"),
                                     borderWidth=1, borderPadding=4),
    }
    return styles


def _header(story, styles, title: str, subtitle: str = "", date_str: str = ""):
    story.append(Paragraph("PharmaFlow AI — Pharmacy Benefit Management", styles["small"]))
    story.append(Paragraph(title, styles["h1"]))
    if subtitle:
        story.append(Paragraph(subtitle, styles["h2"]))
    if date_str:
        story.append(Paragraph(f"Date: {date_str}", styles["small"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a3a5c"),
                            spaceAfter=12))


def _kv_table(data: list[tuple[str, str]], styles) -> Table:
    table_data = [[Paragraph(k, styles["bold"]), Paragraph(str(v), styles["body"])]
                  for k, v in data]
    t = Table(table_data, colWidths=[2.2 * inch, 4.3 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def _footer(story, styles):
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc"),
                            spaceAfter=4))
    story.append(Paragraph(
        "This document is generated by PharmaFlow AI for payer/pharmacist review only. "
        "It is not clinical decision support and must not be used for direct patient care. "
        "All savings estimates are based on CMS NADAC pricing (April 2026). "
        "Member data shown here is synthetic and for demonstration purposes only.",
        styles["disclaimer"],
    ))


# ── Document 1: Member Benefit Letter ────────────────────────────────────────

def _member_letter(rec, today: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            leftMargin=1 * inch, rightMargin=1 * inch,
                            topMargin=1 * inch, bottomMargin=1 * inch)
    s = _styles()
    story = []

    _header(story, s, "Member Benefit Letter", "Drug Benefit Change Notification", today)

    story.append(Paragraph(f"Dear Member {rec.member_id},", s["body"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        f"As part of our ongoing effort to provide you with high-quality, cost-effective pharmacy benefits, "
        f"we have identified an opportunity to change your current prescription to a clinically equivalent "
        f"generic alternative. This change may reduce your out-of-pocket costs.",
        s["body"],
    ))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Proposed Change", s["h2"]))
    story.append(_kv_table([
        ("Current Medication", rec.current_drug),
        ("Proposed Alternative", rec.candidate_alternative),
        ("Equivalence Type", rec.equivalence_type.replace("_", " ").title()),
        ("FDA TE Code", rec.te_code or "See prescriber letter"),
        ("Estimated Gross Savings", f"${rec.gross_savings:,.2f} per fill cycle"),
        ("Risk-Adjusted Savings", f"${rec.risk_adjusted_savings:,.2f} per fill cycle"),
        ("Recommendation", rec.recommendation_band),
    ], s))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("What This Means for You", s["h2"]))
    story.append(Paragraph(
        f"Your prescriber has been notified of this opportunity. If approved, you may begin receiving "
        f"<b>{rec.candidate_alternative}</b> in place of <b>{rec.current_drug}</b> at your next refill. "
        f"No action is required on your part at this time.",
        s["body"],
    ))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Your Rights", s["h2"]))
    story.append(Paragraph(
        "You have the right to request a formulary exception if you and your prescriber believe the "
        "proposed alternative is not appropriate for your medical condition. To appeal or request an "
        "exception, please call the Member Services number on the back of your insurance card.",
        s["body"],
    ))

    _footer(story, s)
    doc.build(story)
    return buf.getvalue()


# ── Document 2: Prescriber Clinical Review Letter ─────────────────────────────

def _prescriber_letter(rec, today: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            leftMargin=1 * inch, rightMargin=1 * inch,
                            topMargin=1 * inch, bottomMargin=1 * inch)
    s = _styles()
    story = []

    _header(story, s, "Prescriber Clinical Review Letter",
            "Generic Substitution — Pharmacist/Clinician Review Requested", today)

    story.append(Paragraph("Dear Prescribing Clinician,", s["body"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        f"Our pharmacy benefit management system has identified a potential generic substitution "
        f"opportunity for member <b>{rec.member_id}</b>. We are requesting your clinical review "
        f"and authorization for the proposed change.",
        s["body"],
    ))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Clinical Equivalence Summary", s["h2"]))
    story.append(_kv_table([
        ("Member ID", rec.member_id),
        ("Current Drug", rec.current_drug),
        ("Proposed Generic", rec.candidate_alternative),
        ("Equivalence Type", rec.equivalence_type.replace("_", " ").title()),
        ("FDA TE Code", rec.te_code or "Not available — clinical review required"),
        ("Mapping Confidence", f"{rec.mapping_confidence * 100:.0f}%"),
        ("Dosage Form / Route", rec.dosage_form_route or "Verify with pharmacist"),
        ("Strength", rec.strength or "Verify with pharmacist"),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Risk Assessment", s["h2"]))
    story.append(_kv_table([
        ("Clinical Risk Score", f"{rec.clinical_risk_score * 100:.0f}%"),
        ("Switch Failure Probability", f"{rec.switch_failure_probability * 100:.0f}%"),
        ("Access Risk Score", f"{rec.access_risk_score * 100:.0f}%"),
        ("Recommendation Band", rec.recommendation_band),
        ("Reason Codes", ", ".join(rec.reason_codes) if rec.reason_codes else "—"),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Clinical Rationale", s["h2"]))
    story.append(Paragraph(rec.explanation or "No additional explanation provided.", s["body"]))

    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("Action Required", s["h2"]))
    story.append(Paragraph(
        "Please review this substitution request and authorize or deny within 10 business days. "
        "If you have clinical concerns, a prior authorization exception can be submitted through "
        "the standard PA portal. If no response is received, the substitution will proceed "
        "at the member's next refill per formulary policy.",
        s["body"],
    ))

    _footer(story, s)
    doc.build(story)
    return buf.getvalue()


# ── Document 3: Pharmacy Network Alignment Notice ────────────────────────────

def _pharmacy_notice(rec, today: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            leftMargin=1 * inch, rightMargin=1 * inch,
                            topMargin=1 * inch, bottomMargin=1 * inch)
    s = _styles()
    story = []

    _header(story, s, "Pharmacy Network Alignment Notice",
            "Formulary Generic Substitution — Dispensing Instructions", today)

    story.append(Paragraph("Dear Dispensing Pharmacist,", s["body"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        "This notice is to inform you of an upcoming formulary change affecting a member in your "
        "network. Please review the substitution details below and ensure the generic alternative "
        "is stocked and ready for dispensing at the member's next refill.",
        s["body"],
    ))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Substitution Details", s["h2"]))
    story.append(_kv_table([
        ("Member ID", rec.member_id),
        ("Brand Drug (Current)", rec.current_drug),
        ("Generic Alternative (New)", rec.candidate_alternative),
        ("Generic NDC", rec.generic_ndc or "Contact PBM for NDC"),
        ("Equivalence Type", rec.equivalence_type.replace("_", " ").title()),
        ("FDA TE Code", rec.te_code or "N/A"),
        ("Formulary Tier Change", "Brand → Generic (Tier reduction expected)"),
        ("Effective Date", today),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Member Access Notes", s["h2"]))
    story.append(_kv_table([
        ("Pharmacy Access Score", f"{rec.access_risk_score * 100:.0f}%"),
        ("Preferred Pharmacy", "Yes" if rec.preferred_pharmacy else "No"),
        ("Member Cost Share Impact", "Reduced copay expected with generic substitution"),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Instructions", s["h2"]))
    story.append(Paragraph(
        "1. Verify the prescriber has authorized the substitution before dispensing.<br/>"
        "2. Ensure the generic NDC listed above is in stock.<br/>"
        "3. Counsel the member on the equivalence of the new medication.<br/>"
        "4. If member declines the generic, contact the PBM to document the refusal.",
        s["body"],
    ))

    _footer(story, s)
    doc.build(story)
    return buf.getvalue()


# ── Document 4: Internal Prior Authorization / UM Memo ───────────────────────

def _internal_memo(rec, today: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            leftMargin=1 * inch, rightMargin=1 * inch,
                            topMargin=1 * inch, bottomMargin=1 * inch)
    s = _styles()
    story = []

    _header(story, s, "Internal Utilization Management Memo",
            "Prior Authorization — Generic Switch Opportunity Analysis", today)

    story.append(Paragraph("CONFIDENTIAL — FOR INTERNAL PAYER USE ONLY", s["bold"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        f"This memo documents the PharmaFlow AI analysis for recommendation <b>{rec.recommendation_id}</b>. "
        f"It is intended for use by the pharmacy benefits, clinical review, and utilization management teams.",
        s["body"],
    ))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Member & Drug Summary", s["h2"]))
    story.append(_kv_table([
        ("Recommendation ID", rec.recommendation_id),
        ("Member ID", rec.member_id),
        ("Current Drug", rec.current_drug),
        ("Generic Alternative", rec.candidate_alternative),
        ("Generic NDC", rec.generic_ndc or "—"),
        ("Equivalence Type", rec.equivalence_type.replace("_", " ").title()),
        ("TE Code", rec.te_code or "—"),
        ("Mapping Confidence", f"{rec.mapping_confidence * 100:.0f}%"),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Financial Analysis (Auditor Agent)", s["h2"]))
    story.append(_kv_table([
        ("Brand Unit Cost", f"${rec.brand_unit_cost:.4f} / unit"),
        ("Generic Unit Cost", f"${rec.generic_unit_cost:.4f} / unit"),
        ("Gross Savings (per fill)", f"${rec.gross_savings:,.2f}"),
        ("Risk-Adjusted Savings", f"${rec.risk_adjusted_savings:,.2f}"),
        ("Savings CI Low", f"${rec.credible_interval_low:,.2f}"),
        ("Savings CI High", f"${rec.credible_interval_high:,.2f}"),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Risk Assessment (Clinician + Social Navigator)", s["h2"]))
    story.append(_kv_table([
        ("Clinical Risk Score", f"{rec.clinical_risk_score * 100:.0f}%"),
        ("Switch Failure Probability", f"{rec.switch_failure_probability * 100:.0f}%"),
        ("Access Risk Score", f"{rec.access_risk_score * 100:.0f}%"),
        ("Adherence Risk", f"{rec.adherence_risk_score * 100:.0f}%"),
        ("Access Override", "YES — Review Required" if rec.access_override else "No"),
        ("Recommendation Band", rec.recommendation_band),
    ], s))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Reason Codes", s["h2"]))
    codes_text = " · ".join(rec.reason_codes) if rec.reason_codes else "—"
    story.append(Paragraph(codes_text, s["body"]))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Clinical Explanation", s["h2"]))
    story.append(Paragraph(rec.explanation or "—", s["body"]))

    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph("Formulary Strategy", s["h2"]))
    if rec.recommendation_band == "Recommend":
        strategy = (
            "Proceed with generic substitution. Low clinical and access risk. "
            "Notify member and prescriber. Update formulary tier at next renewal."
        )
    elif rec.recommendation_band == "Review":
        strategy = (
            "Clinical review required before substitution. Flag for pharmacist follow-up. "
            "Check adherence history and pharmacy access before finalizing switch."
        )
    else:
        strategy = (
            "Do not initiate substitution at this time. Risk-adjusted savings are negative "
            "or clinical/access barriers are present. Revisit at next utilization review cycle."
        )
    story.append(Paragraph(strategy, s["body"]))

    _footer(story, s)
    doc.build(story)
    return buf.getvalue()


# ── Flat context object ───────────────────────────────────────────────────────

class _DocContext:
    """Flat view of a Recommendation for easy template access."""
    def __init__(self, rec):
        self.recommendation_id = rec.recommendation_id
        self.member_id         = rec.member_id
        self.current_drug      = rec.current_drug
        self.candidate_alternative = rec.candidate_alternative
        self.equivalence_type  = rec.equivalence_type
        self.te_code           = rec.te_code or "—"
        self.gross_savings     = rec.gross_savings
        self.risk_adjusted_savings = rec.risk_adjusted_savings
        self.credible_interval_low  = rec.credible_interval_low
        self.credible_interval_high = rec.credible_interval_high
        self.clinical_risk_score    = rec.clinical_risk_score
        self.access_risk_score      = rec.access_risk_score
        self.switch_failure_probability = rec.switch_failure_probability
        self.recommendation_band = rec.recommendation_band
        self.reason_codes  = rec.reason_codes or []
        self.explanation   = rec.explanation or "—"
        # From nested mapping sub-object
        m = rec.mapping
        self.generic_ndc       = m.generic_ndc or "—"
        self.dosage_form_route = m.dosage_form_route or "—"
        self.strength          = m.strength or "—"
        self.mapping_confidence = m.mapping_confidence
        # From nested cost_analysis sub-object
        ca = rec.cost_analysis
        self.brand_unit_cost   = ca.current_unit_cost
        self.generic_unit_cost = ca.alternative_unit_cost
        # From nested access_risk sub-object
        ar = rec.access_risk
        self.adherence_risk_score = ar.adherence_risk_score
        self.access_override      = ar.access_override
        self.preferred_pharmacy   = ar.preferred_pharmacy_available


# ── Public API ────────────────────────────────────────────────────────────────

def generate_switch_package(rec) -> bytes:
    """
    Generate all 4 PDF documents for a Recommendation and return as zip bytes.
    rec: a Recommendation model instance.
    """
    today = date.today().strftime("%B %d, %Y")
    ctx = _DocContext(rec)

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("member_letter.pdf",      _member_letter(ctx, today))
        zf.writestr("prescriber_letter.pdf",  _prescriber_letter(ctx, today))
        zf.writestr("pharmacy_notice.pdf",    _pharmacy_notice(ctx, today))
        zf.writestr("internal_memo.pdf",      _internal_memo(ctx, today))

    return zip_buf.getvalue()
